---
# personal repository; https://forge.chirality.de/thorou/-/packages?q=&type=debian

- name: personal-repo
  gather_facts: false
  hosts: all
  tasks:
    - name: add thorou signing key
      become: true
      get_url:
        url: "https://forge.chirality.de/api/packages/thorou/debian/repository.key"
        dest: /etc/apt/keyrings/thorou-personal-repo.asc
        mode: "644"

    - name: Add thorou repository to apt sources
      become: true
      apt_repository:
        filename: thorou-personal-repo
        repo: deb [signed-by=/etc/apt/keyrings/thorou-personal-repo.asc] https://forge.chirality.de/api/packages/thorou/debian generic main
        update_cache: true
